# Generated by Django 6.0.3 on 2026-03-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trade_capital_base_trade_lot_size_trade_risk_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='trades/screenshots/'),
        ),
    ]
