# Generated by Django 6.0.3 on 2026-03-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_trade_gp_value_trade_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpreference',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar americain (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Livre sterling (GBP)'), ('CHF', 'Franc suisse (CHF)'), ('XAF', 'Franc CFA BEAC (XAF)'), ('XOF', 'Franc CFA BCEAO (XOF)')], default='USD', max_length=3),
        ),
    ]
