# Generated by Django 6.0.3 on 2026-03-21 08:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_default_trading_accounts(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    TradingPreference = apps.get_model('app', 'TradingPreference')
    TradingAccount = apps.get_model('app', 'TradingAccount')
    Trade = apps.get_model('app', 'Trade')
    CapitalMovement = apps.get_model('app', 'CapitalMovement')

    for user in User.objects.all().iterator():
        preference = TradingPreference.objects.filter(user_id=user.pk).first()
        capital_base = getattr(preference, 'capital_base', Decimal('10000.00')) or Decimal('10000.00')
        currency = getattr(preference, 'currency', 'USD') or 'USD'

        account = TradingAccount.objects.create(
            user_id=user.pk,
            name='Compte principal',
            capital_base=capital_base,
            currency=currency,
        )

        if preference and not preference.active_account_id:
            preference.active_account_id = account.pk
            preference.save(update_fields=['active_account'])

        Trade.objects.filter(user_id=user.pk, account__isnull=True).update(account_id=account.pk)
        CapitalMovement.objects.filter(user_id=user.pk, account__isnull=True).update(account_id=account.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_trade_risk_amount_alter_trade_risk_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Compte principal', max_length=80)),
                ('broker', models.CharField(blank=True, max_length=80)),
                ('account_identifier', models.CharField(blank=True, max_length=80)),
                ('capital_base', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('currency', models.CharField(choices=[('USD', 'Dollar americain (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Livre sterling (GBP)'), ('CHF', 'Franc suisse (CHF)'), ('XAF', 'Franc CFA BEAC (XAF)'), ('XOF', 'Franc CFA BCEAO (XOF)')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='capitalmovement',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_movements', to='app.tradingaccount'),
        ),
        migrations.AddField(
            model_name='trade',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='app.tradingaccount'),
        ),
        migrations.AddField(
            model_name='tradingpreference',
            name='active_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_preferences', to='app.tradingaccount'),
        ),
        migrations.RunPython(seed_default_trading_accounts, migrations.RunPython.noop),
    ]
