# Generated by Django 6.0.3 on 2026-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tradingaccount_capitalmovement_account_trade_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
