# Generated by Django 6.0.3 on 2026-03-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tradingpreference_ui_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=60)),
                ('platform', models.CharField(choices=[('WEBSITE', 'Website'), ('X', 'X'), ('INSTAGRAM', 'Instagram'), ('TELEGRAM', 'Telegram'), ('YOUTUBE', 'YouTube'), ('LINKEDIN', 'LinkedIn'), ('FACEBOOK', 'Facebook'), ('DISCORD', 'Discord'), ('GITHUB', 'GitHub'), ('TIKTOK', 'TikTok')], max_length=20)),
                ('url', models.URLField(max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lien social',
                'verbose_name_plural': 'Liens sociaux',
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
