# Generated by Django 5.1.2 on 2026-03-21 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRefreshStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suivi actualisation serveur',
                'verbose_name_plural': 'Suivi actualisation serveur',
            },
        ),
    ]
