# Generated by Django 6.0.3 on 2026-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_normalize_ui_language_to_fr_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(
                choices=[
                    ('WEBSITE', 'Website'),
                    ('X', 'X'),
                    ('INSTAGRAM', 'Instagram'),
                    ('WHATSAPP', 'WhatsApp'),
                    ('TELEGRAM', 'Telegram'),
                    ('YOUTUBE', 'YouTube'),
                    ('LINKEDIN', 'LinkedIn'),
                    ('FACEBOOK', 'Facebook'),
                    ('DISCORD', 'Discord'),
                    ('GITHUB', 'GitHub'),
                    ('TIKTOK', 'TikTok'),
                ],
                max_length=20,
            ),
        ),
    ]
