# Generated by Django 6.0.3 on 2026-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sociallink_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trades/screenshots/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='screenshots', to='app.trade')),
            ],
            options={
                'verbose_name': 'Image de trade',
                'verbose_name_plural': 'Images de trade',
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
