# Generated by Django 6.0.3 on 2026-04-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_tradingpreference_default_week_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpreference',
            name='ui_language',
            field=models.CharField(choices=[('fr', 'Francais'), ('en', 'English')], default='fr', max_length=12),
        ),
    ]
