from django.utils.translation import get_language

DEFAULT_LANGUAGE = "fr"
RTL_LANGUAGES = {"ar"}


def pack(fr, en, es=None, pt=None, ar=None, zh=None):
    return {
        "fr": fr,
        "en": en,
        "es": es or en,
        "pt": pt or en,
        "ar": ar or en,
        "zh-hans": zh or en,
    }


LANGUAGE_META = {
    "fr": {"native_name": "Francais", "english_name": "French", "locale": "fr-FR"},
    "en": {"native_name": "English", "english_name": "English", "locale": "en-US"},
    "es": {"native_name": "Espanol", "english_name": "Spanish", "locale": "es-ES"},
    "pt": {"native_name": "Portugues", "english_name": "Portuguese", "locale": "pt-BR"},
    "ar": {"native_name": "Arabic", "english_name": "Arabic", "locale": "ar-SA"},
    "zh-hans": {"native_name": "Chinese", "english_name": "Chinese", "locale": "zh-CN"},
}

WEEKDAY_SHORT = {
    "fr": ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"],
    "en": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "es": ["Lun", "Mar", "Mie", "Jue", "Vie", "Sab", "Dom"],
    "pt": ["Seg", "Ter", "Qua", "Qui", "Sex", "Sab", "Dom"],
    "ar": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "zh-hans": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
}

TRANSLATIONS = {
    "brand.meta_description": pack("ZEN TRADING est une plateforme de journal de trading pour piloter vos comptes, votre capital, vos performances et votre discipline depuis un espace unique.", "ZEN TRADING is a trading journal platform to manage your accounts, capital, performance, and discipline from one workspace.", "ZEN TRADING es una plataforma de diario de trading para gestionar sus cuentas, capital, rendimiento y disciplina desde un solo espacio.", "ZEN TRADING e uma plataforma de diario de trading para gerir contas, capital, performance e disciplina em um unico espaco."),
    "brand.subtitle": pack("Plateforme de performance", "Performance platform", "Plataforma de rendimiento", "Plataforma de performance"),
    "language.switch": pack("Changer la langue", "Change language", "Cambiar idioma", "Alterar idioma"),
    "language.title": pack("Langue de l'application", "Application language", "Idioma de la aplicacion", "Idioma da aplicacao"),
    "language.subtitle": pack("Selectionnez la langue d'affichage principale.", "Select the main display language.", "Seleccione el idioma principal de visualizacion.", "Selecione o idioma principal de exibicao."),
    "nav.dashboard": pack("Dashboard", "Dashboard", "Panel", "Dashboard"),
    "nav.transactions": pack("Transactions", "Transactions", "Transacciones", "Transacoes"),
    "nav.tools": pack("Outils", "Tools", "Herramientas", "Ferramentas"),
    "nav.setups": pack("Setups", "Setups", "Setups", "Setups"),
    "nav.settings": pack("Parametres", "Settings", "Configuracion", "Configuracoes"),
    "common.refresh": pack("Rafraichir", "Refresh", "Actualizar", "Atualizar"),
    "common.period": pack("Periode", "Period", "Periodo", "Periodo"),
    "common.logout": pack("Se deconnecter", "Sign out", "Cerrar sesion", "Sair"),
    "common.logout_loading": pack("Deconnexion...", "Signing out...", "Cerrando sesion...", "Saindo..."),
    "common.main_account": pack("Compte principal", "Main account", "Cuenta principal", "Conta principal"),
    "common.broker_missing": pack("Broker non renseigne", "Broker not specified", "Broker no informado", "Broker nao informado"),
    "common.close_account_switch": pack("Fermer le changement de compte", "Close account switcher", "Cerrar cambio de cuenta", "Fechar troca de conta"),
    "common.super_admin": pack("Super admin", "Super admin", "Super admin", "Super admin"),
    "trade.direction.long": pack("Long", "Long", "Long", "Long"),
    "trade.direction.short": pack("Short", "Short", "Short", "Short"),
    "trade.result.take_profit": pack("Take profit", "Take profit", "Take profit", "Take profit"),
    "trade.result.break_even": pack("Break even", "Break even", "Break even", "Break even"),
    "trade.result.stop_loss": pack("Stoploss", "Stop loss", "Stop loss", "Stop loss"),
    "auth.page.login": pack("Connexion", "Sign in", "Iniciar sesion", "Entrar"),
    "auth.page.register": pack("Inscription", "Register", "Registro", "Cadastro"),
    "auth.hero.badge": pack("Trading Journal Asynchrone", "Asynchronous trading journal", "Journal de trading asincrono", "Journal de trading assincrono"),
    "auth.hero.title": pack("Un journal de trading clair, rapide et structure.", "A trading journal that is clear, fast, and structured.", "Un diario de trading claro, rapido y estructurado.", "Um diario de trading claro, rapido e estruturado."),
    "auth.hero.copy": pack("Suivez vos comptes, votre capital et vos performances depuis une interface unique.", "Track your accounts, capital, and performance from one unified workspace.", "Siga sus cuentas, su capital y su rendimiento desde una sola interfaz.", "Acompanhe suas contas, capital e performance em uma unica interface."),
    "auth.brand.note": pack("ZEN TRADING centralise votre journal, votre capital, votre discipline et vos outils de pilotage dans un espace de suivi professionnel.", "ZEN TRADING centralizes your journal, capital, discipline, and decision tools in one professional trading workspace.", "ZEN TRADING centraliza su diario, su capital, su disciplina y sus herramientas de pilotaje en un espacio profesional.", "ZEN TRADING centraliza seu diario, capital, disciplina e ferramentas de pilotagem em um espaco profissional."),
    "auth.meta_description": pack("Connectez-vous a ZEN TRADING pour suivre vos comptes, votre capital, vos performances et votre discipline de trading dans un environnement professionnel.", "Sign in to ZEN TRADING to track your accounts, capital, performance, and trading discipline in a professional workspace.", "Acceda a ZEN TRADING para seguir sus cuentas, capital, rendimiento y disciplina de trading en un entorno profesional.", "Acesse o ZEN TRADING para acompanhar contas, capital, performance e disciplina de trading em um ambiente profissional."),
    "auth.hero.stat.access": pack("Acces", "Access", "Acceso", "Acesso"),
    "auth.hero.stat.secure": pack("Securise", "Secure", "Seguro", "Seguro"),
    "auth.hero.stat.dashboard": pack("Dashboard", "Dashboard", "Panel", "Dashboard"),
    "auth.hero.stat.async": pack("Asynchrone", "Asynchronous", "Asincrono", "Assincrono"),
    "auth.hero.stat.monitoring": pack("Suivi", "Tracking", "Seguimiento", "Acompanhamento"),
    "auth.hero.stat.multi_accounts": pack("Multi-comptes", "Multi-account", "Multicuentas", "Multicontas"),
    "auth.hero.tape.radar": pack("Radar de performance", "Performance radar", "Radar de rendimiento", "Radar de performance"),
    "auth.hero.tape.calendar": pack("Calendrier mensuel", "Monthly calendar", "Calendario mensual", "Calendario mensal"),
    "auth.hero.tape.transactions": pack("Transactions de capital", "Capital transactions", "Transacciones de capital", "Transacoes de capital"),
    "auth.social.title": pack("Contact rapide", "Quick contact", "Contacto rapido", "Contato rapido"),
    "auth.social.copy": pack("Retrouvez nos canaux officiels pour poser une question ou demander une assistance.", "Use our official channels to ask a question or request support.", "Utilice nuestros canales oficiales para hacer una pregunta o solicitar asistencia.", "Use nossos canais oficiais para tirar uma duvida ou solicitar suporte."),
    "auth.login.eyebrow": pack("Connexion", "Sign in", "Inicio de sesion", "Entrar"),
    "auth.register.eyebrow": pack("Inscription", "Register", "Registro", "Cadastro"),
    "auth.login.title": pack("Acceder a votre espace", "Access your workspace", "Acceda a su espacio", "Acesse seu espaco"),
    "auth.register.title": pack("Creer votre espace", "Create your workspace", "Cree su espacio", "Crie seu espaco"),
    "auth.login.copy": pack("Connectez-vous pour retrouver votre environnement de trading.", "Sign in to access your trading environment.", "Inicie sesion para recuperar su entorno de trading.", "Entre para acessar seu ambiente de trading."),
    "auth.register.copy": pack("Creez votre espace pour commencer a journaliser vos executions.", "Create your workspace to start logging your executions.", "Cree su espacio para comenzar a registrar sus ejecuciones.", "Crie seu espaco para comecar a registrar suas execucoes."),
    "auth.login.badge": pack("Session protegee", "Protected session", "Sesion protegida", "Sessao protegida"),
    "auth.register.badge": pack("Activation immediate", "Instant activation", "Activacion inmediata", "Ativacao imediata"),
    "auth.password.title": pack("Exigences du mot de passe", "Password requirements", "Requisitos de la contrasena", "Requisitos da senha"),
    "auth.password.length": pack("Au moins 8 caracteres", "At least 8 characters", "Al menos 8 caracteres", "Pelo menos 8 caracteres"),
    "auth.password.numeric": pack("Ne pas utiliser uniquement des chiffres", "Do not use only numbers", "No use solo numeros", "Nao use apenas numeros"),
    "auth.password.personal": pack("Eviter les informations personnelles evidentes", "Avoid obvious personal information", "Evite informacion personal evidente", "Evite informacoes pessoais obvias"),
    "auth.password.common": pack("Eviter les mots de passe trop courants", "Avoid common passwords", "Evite contrasenas comunes", "Evite senhas comuns"),
    "auth.login.submit": pack("Se connecter", "Sign in", "Entrar", "Entrar"),
    "auth.register.submit": pack("Creer le compte", "Create account", "Crear cuenta", "Criar conta"),
    "auth.login.footer": pack("Authentification serveur et ouverture de session securisee.", "Server-side authentication with a secure session.", "Autenticacion del servidor con sesion segura.", "Autenticacao no servidor com sessao segura."),
    "auth.register.footer": pack("L espace est disponible immediatement apres creation du compte.", "Your workspace is available immediately after registration.", "Su espacio estara disponible inmediatamente despues del registro.", "Seu espaco fica disponivel imediatamente apos o cadastro."),
    "auth.login.switch_prompt": pack("Vous n avez pas encore de compte ?", "Do not have an account yet?", "Aun no tiene una cuenta?", "Ainda nao tem uma conta?"),
    "auth.register.switch_prompt": pack("Vous avez deja un compte ?", "Already have an account?", "Ya tiene una cuenta?", "Ja possui uma conta?"),
    "auth.login.switch_link": pack("Creer un compte", "Create an account", "Crear una cuenta", "Criar uma conta"),
    "auth.register.switch_link": pack("Se connecter", "Sign in", "Iniciar sesion", "Entrar"),
    "form.login.username": pack("Identifiant", "Username", "Usuario", "Usuario"),
    "form.login.username.placeholder": pack("Ex: mikefx", "Example: mikefx", "Ej: mikefx", "Ex: mikefx"),
    "form.password": pack("Mot de passe", "Password", "Contrasena", "Senha"),
    "form.password.placeholder": pack("Votre mot de passe", "Your password", "Su contrasena", "Sua senha"),
    "form.email": pack("Email", "Email", "Correo", "Email"),
    "form.first_name": pack("Prenom", "First name", "Nombre", "Nome"),
    "form.first_name.placeholder": pack("Prenom", "First name", "Nombre", "Nome"),
    "form.password.confirmation": pack("Confirmation", "Confirmation", "Confirmacion", "Confirmacao"),
    "form.password.new.placeholder": pack("Minimum 8 caracteres", "Minimum 8 characters", "Minimo 8 caracteres", "Minimo 8 caracteres"),
    "form.password.confirmation.placeholder": pack("Confirmez le mot de passe", "Confirm password", "Confirme la contrasena", "Confirme a senha"),
    "dashboard.page.title": pack("Dashboard", "Dashboard", "Panel", "Dashboard"),
    "dashboard.sidebar.score": pack("Score global", "Global score", "Puntuacion global", "Score global"),
    "dashboard.sidebar.loading": pack("Chargement...", "Loading...", "Cargando...", "Carregando..."),
    "dashboard.sidebar.all_time_pnl": pack("All-time P&L", "All-time P&L", "P&L total", "P&L total"),
    "dashboard.sidebar.total_trades": pack("Total trades", "Total trades", "Total trades", "Total de trades"),
    "dashboard.sidebar.leading_setup": pack("Setup leader", "Leading setup", "Setup lider", "Setup lider"),
    "dashboard.header.eyebrow": pack("Journal de trading", "Trading journal", "Diario de trading", "Journal de trading"),
    "dashboard.header.title": pack("Dashboard de performance", "Performance dashboard", "Panel de rendimiento", "Dashboard de performance"),
    "dashboard.header.copy": pack("Bonjour {user_name}, suivez la performance du compte actif, enregistrez vos executions et actualisez le tableau de bord en temps reel.", "Hello {user_name}, track the active account, log your executions, and refresh the dashboard in real time.", "Hola {user_name}, siga la cuenta activa, registre sus ejecuciones y actualice el panel en tiempo real.", "Ola {user_name}, acompanhe a conta ativa, registre suas execucoes e atualize o dashboard em tempo real."),
    "dashboard.new_trade": pack("Nouveau trade", "New trade", "Nuevo trade", "Novo trade"),
    "dashboard.load_demo": pack("Charger des donnees de demonstration", "Load demo data", "Cargar datos de demostracion", "Carregar dados de demonstracao"),
    "dashboard.demo.super_admin_only": pack("Action reservee au super administrateur.", "This action is restricted to the super admin.", "Esta accion esta reservada al super administrador.", "Esta acao e reservada ao super administrador."),
    "dashboard.sync.title": pack("Synchronisation asynchrone", "Asynchronous sync", "Sincronizacion asincrona", "Sincronizacao assincrona"),
    "dashboard.sync.init": pack("Initialisation du tableau de bord en cours...", "Initializing dashboard...", "Inicializando panel...", "Inicializando dashboard..."),
    "dashboard.loader.title": pack("Synchronisation du dashboard", "Dashboard sync", "Sincronizacion del panel", "Sincronizacao do dashboard"),
    "dashboard.loader.copy": pack("Chargement des indicateurs, graphiques, calendrier et executions recentes.", "Loading metrics, charts, calendar, and recent executions.", "Cargando metricas, graficos, calendario y ejecuciones recientes.", "Carregando metricas, graficos, calendario e execucoes recentes."),
    "dashboard.panel.capture.badge": pack("Modale asynchrone", "Asynchronous modal", "Modal asincrono", "Modal assincrono"),
    "dashboard.panel.capture.copy": pack("Ouvrez la fenetre de saisie pour enregistrer une execution sans interrompre la consultation du tableau de bord. Apres validation, les indicateurs, graphiques et le calendrier sont actualises automatiquement.", "Open the entry window to log an execution without interrupting the dashboard. After submission, metrics, charts, and the calendar refresh automatically.", "Abra la ventana de registro para guardar una ejecucion sin interrumpir el panel. Tras validar, las metricas, graficos y el calendario se actualizan automaticamente.", "Abra a janela de entrada para registrar uma execucao sem interromper o dashboard. Apos a validacao, metricas, graficos e calendario sao atualizados automaticamente."),
    "dashboard.panel.capture.point_one": pack("Ratio et G/P", "Ratio and P/L", "Ratio y G/P", "Ratio e G/P"),
    "dashboard.panel.capture.point_two": pack("Volume et impact capital", "Volume and capital impact", "Volumen e impacto en capital", "Volume e impacto no capital"),
    "dashboard.panel.capture.point_three": pack("Resultat, setup et commentaires", "Outcome, setup, and notes", "Resultado, setup y notas", "Resultado, setup e observacoes"),
    "dashboard.add_trade": pack("Ajouter un trade", "Add trade", "Agregar trade", "Adicionar trade"),
    "transactions.page.title": pack("Transactions", "Transactions", "Transacciones", "Transacoes"),
    "transactions.sidebar.current_capital": pack("Capital actuel", "Current capital", "Capital actual", "Capital atual"),
    "transactions.sidebar.trades_month": pack("Trades ce mois", "Trades this month", "Trades del mes", "Trades do mes"),
    "transactions.sidebar.winners": pack("Gagnants", "Winners", "Ganadores", "Vencedores"),
    "transactions.sidebar.losers": pack("Perdants", "Losers", "Perdedores", "Perdedores"),
    "transactions.header.eyebrow": pack("Flux de capital", "Capital flow", "Flujo de capital", "Fluxo de capital"),
    "transactions.header.title": pack("Transactions", "Transactions", "Transacciones", "Transacoes"),
    "transactions.header.copy": pack("Analysez l historique mensuel du G/P, les depots et les retraits du compte actif, avec recalcul automatique du capital et des indicateurs.", "Analyze monthly P/L history, deposits, and withdrawals for the active account with automatic capital recalculation.", "Analice el historial mensual de G/P, depositos y retiros de la cuenta activa con recalculo automatico del capital.", "Analise o historico mensal de G/P, depositos e retiradas da conta ativa com recalculo automatico do capital."),
    "transactions.new_withdrawal": pack("Nouveau retrait", "New withdrawal", "Nuevo retiro", "Nova retirada"),
    "transactions.new_deposit": pack("Nouveau depot", "New deposit", "Nuevo deposito", "Novo deposito"),
    "transactions.sync.init": pack("Initialisation des transactions en cours...", "Initializing transactions...", "Inicializando transacciones...", "Inicializando transacoes..."),
    "transactions.sidebar.pending_sync": pack("Base {capital} | Synchronisation en attente.", "Base {capital} | Sync pending.", "Base {capital} | Sincronizacion pendiente.", "Base {capital} | Sincronizacao pendente."),
    "transactions.loader.title": pack("Synchronisation des transactions", "Transactions sync", "Sincronizacion de transacciones", "Sincronizacao de transacoes"),
    "transactions.loader.copy": pack("Chargement du capital, des flux et de l historique mensuel.", "Loading capital, flows, and monthly history.", "Cargando capital, flujos e historial mensual.", "Carregando capital, fluxos e historico mensal."),
    "transactions.history.month": pack("Mois", "Month", "Mes", "Mes"),
    "transactions.history.capital_start": pack("Capital debut", "Starting capital", "Capital inicial", "Capital inicial"),
    "transactions.history.deposits": pack("Depots", "Deposits", "Depositos", "Depositos"),
    "transactions.history.withdrawals": pack("Retraits", "Withdrawals", "Retiros", "Retiradas"),
    "transactions.history.net": pack("Net", "Net", "Neto", "Liquido"),
    "transactions.history.trades": pack("Trades", "Trades", "Trades", "Trades"),
    "transactions.history.winners": pack("Gagnants", "Winners", "Ganadores", "Vencedores"),
    "transactions.history.losers": pack("Perdants", "Losers", "Perdedores", "Perdedores"),
    "settings.page.title": pack("Parametres", "Settings", "Configuracion", "Configuracoes"),
    "settings.header.eyebrow": pack("Configuration", "Configuration", "Configuracion", "Configuracao"),
    "settings.header.title": pack("Parametres de trading", "Trading settings", "Configuracion de trading", "Configuracoes de trading"),
    "settings.header.copy": pack("Centralisez les parametres du compte actif, les valeurs de saisie par defaut et les options de securite. Le capital actuel reste dynamique, tandis que le capital initial demeure la reference historique.", "Centralize active account settings, default entry values, and security options. Current capital stays dynamic while initial capital remains the historical reference.", "Centralice la configuracion de la cuenta activa, los valores por defecto y las opciones de seguridad. El capital actual sigue siendo dinamico, mientras que el capital inicial permanece como referencia historica.", "Centralize as configuracoes da conta ativa, os valores padrao de entrada e as opcoes de seguranca. O capital atual permanece dinamico enquanto o capital inicial continua como referencia historica."),
    "settings.back_dashboard": pack("Retour au dashboard", "Back to dashboard", "Volver al panel", "Voltar ao dashboard"),
    "settings.sidebar.capital": pack("Capital actif", "Active capital", "Capital activo", "Capital ativo"),
    "settings.sidebar.capital_copy": pack("Capital consolide du compte actif, calcule a partir des trades et des mouvements de capital.", "Consolidated capital of the active account, calculated from trades and capital movements.", "Capital consolidado de la cuenta activa, calculado a partir de trades y movimientos de capital.", "Capital consolidado da conta ativa, calculado a partir dos trades e movimentos de capital."),
    "settings.sidebar.active_account": pack("Compte actif", "Active account", "Cuenta activa", "Conta ativa"),
    "settings.sidebar.broker": pack("Broker", "Broker", "Broker", "Broker"),
    "settings.sidebar.currency": pack("Devise", "Currency", "Moneda", "Moeda"),
    "settings.accounts.kicker": pack("Comptes", "Accounts", "Cuentas", "Contas"),
    "settings.accounts.title": pack("Comptes de trading", "Trading accounts", "Cuentas de trading", "Contas de trading"),
    "settings.accounts.count_suffix": pack("compte(s)", "account(s)", "cuenta(s)", "conta(s)"),
    "settings.accounts.show_archived": pack("Afficher les comptes archives", "Show archived accounts", "Mostrar cuentas archivadas", "Exibir contas arquivadas"),
    "settings.accounts.archived_title": pack("Comptes archives", "Archived accounts", "Cuentas archivadas", "Contas arquivadas"),
    "settings.accounts.add": pack("Ajouter un compte", "Add account", "Agregar cuenta", "Adicionar conta"),
    "settings.accounts.section_title": pack("Compte actif", "Active account", "Cuenta activa", "Conta ativa"),
    "settings.accounts.section_copy": pack("Un meme utilisateur peut administrer plusieurs comptes de trading. Selectionnez ici le compte actif utilise dans le dashboard et le module Transactions.", "A single user can manage multiple trading accounts. Select the active account used in the dashboard and Transactions module.", "Un mismo usuario puede administrar varias cuentas de trading. Seleccione aqui la cuenta activa usada en el panel y en el modulo de Transacciones.", "Um mesmo usuario pode administrar varias contas de trading. Selecione aqui a conta ativa usada no dashboard e no modulo de Transacoes."),
    "settings.account.active_badge": pack("Actif", "Active", "Activa", "Ativa"),
    "settings.account.activate": pack("Activer", "Activate", "Activar", "Ativar"),
    "settings.account.activate_loading": pack("Activation...", "Activating...", "Activando...", "Ativando..."),
    "dashboard.switch_account_aria": pack("Changer rapidement de compte de trading", "Quickly switch trading account", "Cambiar rapidamente de cuenta de trading", "Trocar rapidamente de conta de trading"),
    "calendar.week": pack("Semaine {index}", "Week {index}", "Semana {index}", "Semana {index}"),
    "dashboard.panel.radar": pack("Radar", "Radar", "Radar", "Radar"),
    "dashboard.panel.score": pack("Score performance", "Performance score", "Puntuacion de rendimiento", "Score de performance"),
    "dashboard.panel.expand_radar": pack("Agrandir le radar", "Expand radar", "Ampliar radar", "Ampliar radar"),
    "dashboard.panel.curve": pack("Courbe", "Curve", "Curva", "Curva"),
    "dashboard.panel.cumulative": pack("P&L cumulatif", "Cumulative P&L", "P&L acumulado", "P&L cumulativo"),
    "dashboard.panel.expand_curve": pack("Agrandir la courbe", "Expand curve", "Ampliar curva", "Ampliar curva"),
    "dashboard.panel.daily": pack("Quotidien", "Daily", "Diario", "Diario"),
    "dashboard.panel.daily_title": pack("Net P&L quotidien", "Daily net P&L", "P&L neto diario", "P&L liquido diario"),
    "dashboard.panel.expand_daily": pack("Agrandir la vue quotidienne", "Expand daily view", "Ampliar vista diaria", "Ampliar vista diaria"),
    "dashboard.panel.combo": pack("Vue combinee", "Combined view", "Vista combinada", "Vista combinada"),
    "dashboard.panel.combo_title": pack("Net P&L quotidien et cumulatif", "Daily and cumulative net P&L", "P&L neto diario y acumulado", "P&L liquido diario e cumulativo"),
    "dashboard.panel.expand_combo": pack("Agrandir la vue combinee", "Expand combined view", "Ampliar vista combinada", "Ampliar vista combinada"),
    "dashboard.panel.calendar": pack("Calendrier", "Calendar", "Calendario", "Calendario"),
    "dashboard.panel.calendar_title": pack("Calendrier de performance", "Performance calendar", "Calendario de rendimiento", "Calendario de performance"),
    "dashboard.panel.expand_calendar": pack("Agrandir le calendrier", "Expand calendar", "Ampliar calendario", "Ampliar calendario"),
    "dashboard.panel.activity": pack("Activite", "Activity", "Actividad", "Atividade"),
    "dashboard.panel.recent_trades": pack("Executions recentes", "Recent executions", "Ejecuciones recientes", "Execucoes recentes"),
    "dashboard.panel.capture_kicker": pack("Capture", "Capture", "Captura", "Captura"),
    "dashboard.panel.capture_title": pack("Saisie rapide", "Quick entry", "Entrada rapida", "Entrada rapida"),
    "dashboard.score.loading": pack("Analyse en cours...", "Analysis in progress...", "Analisis en curso...", "Analise em andamento..."),
    "dashboard.trade_modal.new": pack("Nouveau trade", "New trade", "Nuevo trade", "Novo trade"),
    "dashboard.trade_modal.edit": pack("Modifier le trade", "Edit trade", "Editar trade", "Editar trade"),
    "dashboard.trade_modal.copy": pack("Renseignez l execution ici. L enregistrement reste asynchrone et le tableau de bord est actualise apres validation.", "Enter the execution here. Saving stays asynchronous and the dashboard refreshes after submission.", "Introduzca la ejecucion aqui. El registro sigue siendo asincrono y el panel se actualiza tras validar.", "Informe a execucao aqui. O registro continua assincrono e o dashboard e atualizado apos a validacao."),
    "dashboard.trade_modal.close": pack("Fermer la fenetre", "Close window", "Cerrar ventana", "Fechar janela"),
    "dashboard.trade_form.executed_at": pack("Date et heure", "Date and time", "Fecha y hora", "Data e hora"),
    "dashboard.trade_form.symbol": pack("Symbole", "Symbol", "Simbolo", "Simbolo"),
    "dashboard.trade_form.direction": pack("Direction", "Direction", "Direccion", "Direcao"),
    "dashboard.trade_form.setup": pack("Setup", "Setup", "Setup", "Setup"),
    "dashboard.trade_form.confidence": pack("Confiance", "Confidence", "Confianza", "Confianca"),
    "dashboard.trade_form.ratio": pack("Ratio", "Ratio", "Ratio", "Ratio"),
    "dashboard.trade_form.result": pack("Resultat", "Result", "Resultado", "Resultado"),
    "dashboard.trade_form.lots": pack("Quantite (lots)", "Size (lots)", "Cantidad (lotes)", "Quantidade (lotes)"),
    "dashboard.trade_form.gp": pack("G/P", "P/L", "G/P", "G/P"),
    "dashboard.trade_form.capital_gain": pack("Gain sur capital (%)", "Capital gain (%)", "Ganancia sobre capital (%)", "Ganho sobre capital (%)"),
    "dashboard.trade_form.capital_loss": pack("Perte sur capital (%)", "Capital loss (%)", "Perdida sobre capital (%)", "Perda sobre capital (%)"),
    "dashboard.trade_form.capital_impact": pack("Impact sur capital (%)", "Capital impact (%)", "Impacto sobre capital (%)", "Impacto sobre capital (%)"),
    "dashboard.trade_form.capital_hint": pack("Calcul base sur un capital actuel de {capital}.", "Calculated from the current capital of {capital}.", "Calculado sobre el capital actual de {capital}.", "Calculado com base no capital atual de {capital}."),
    "dashboard.trade_form.capital_help": pack("TP = gain, SL = perte, BE = 0.00%.", "TP = gain, SL = loss, BE = 0.00%.", "TP = ganancia, SL = perdida, BE = 0.00%.", "TP = ganho, SL = perda, BE = 0.00%."),
    "dashboard.trade_form.image": pack("Image du trade", "Trade image", "Imagen del trade", "Imagem do trade"),
    "dashboard.trade_form.image_help": pack("Image compressee automatiquement avant televersement.", "Image is compressed automatically before upload.", "La imagen se comprime automaticamente antes de subirla.", "A imagem e comprimida automaticamente antes do envio."),
    "dashboard.trade_form.preview_empty": pack("Aucun fichier selectionne", "No file selected", "Ningun archivo seleccionado", "Nenhum arquivo selecionado"),
    "dashboard.trade_form.notes": pack("Notes", "Notes", "Notas", "Notas"),
    "dashboard.trade_form.notes_placeholder": pack("Contexte, execution, gestion du risque, observations...", "Context, execution, risk management, notes...", "Contexto, ejecucion, gestion del riesgo, observaciones...", "Contexto, execucao, gestao de risco, observacoes..."),
    "dashboard.trade_form.submit_caption": pack("Le trade est enregistre puis le tableau de bord est actualise automatiquement.", "The trade is saved and the dashboard refreshes automatically.", "El trade se guarda y el panel se actualiza automaticamente.", "O trade e salvo e o dashboard e atualizado automaticamente."),
    "dashboard.trade_form.submit": pack("Enregistrer le trade", "Save trade", "Guardar trade", "Salvar trade"),
    "dashboard.modal.expand": pack("Agrandissement", "Expanded view", "Vista ampliada", "Vista ampliada"),
    "dashboard.modal.detailed_view": pack("Vue detaillee", "Detailed view", "Vista detallada", "Vista detalhada"),
    "dashboard.modal.close_expand": pack("Fermer l agrandissement", "Close expanded view", "Cerrar vista ampliada", "Fechar vista ampliada"),
    "dashboard.modal.details": pack("Details", "Details", "Detalles", "Detalhes"),
    "dashboard.modal.trade": pack("Trade", "Trade", "Trade", "Trade"),
    "dashboard.modal.loading_detail": pack("Chargement du detail...", "Loading details...", "Cargando detalles...", "Carregando detalhes..."),
    "dashboard.modal.close_details": pack("Fermer les details", "Close details", "Cerrar detalles", "Fechar detalhes"),
    "dashboard.metric.net_pnl": pack("Net P&L", "Net P&L", "P&L neto", "P&L liquido"),
    "dashboard.metric.net_pnl_detail": pack("{count} trade(s) sur la periode selectionnee", "{count} trade(s) over the selected period", "{count} trade(s) en el periodo seleccionado", "{count} trade(s) no periodo selecionado"),
    "dashboard.metric.win_rate": pack("Taux de reussite", "Win rate", "Tasa de acierto", "Taxa de acerto"),
    "dashboard.metric.win_rate_detail": pack("{winners} trade(s) gagnants / {count}", "{winners} winning trade(s) / {count}", "{winners} trade(s) ganadores / {count}", "{winners} trade(s) vencedores / {count}"),
    "dashboard.metric.profit_factor": pack("Profit factor", "Profit factor", "Profit factor", "Profit factor"),
    "dashboard.metric.profit_factor_detail": pack("Ratio gains / pertes", "Gains / losses ratio", "Relacion ganancias / perdidas", "Relacao ganhos / perdas"),
    "dashboard.metric.positive_days": pack("Jours positifs", "Positive days", "Dias positivos", "Dias positivos"),
    "dashboard.metric.positive_days_detail": pack("{days} jour(s) positifs / {active_days}", "{days} positive day(s) / {active_days}", "{days} dia(s) positivos / {active_days}", "{days} dia(s) positivos / {active_days}"),
    "dashboard.metric.avg_trade": pack("Moyenne / trade", "Average / trade", "Promedio / trade", "Media / trade"),
    "dashboard.metric.avg_trade_detail": pack("Ratio moyen gain / perte : {ratio}", "Average gain / loss ratio: {ratio}", "Relacion media ganancia / perdida: {ratio}", "Relacao media ganho / perda: {ratio}"),
    "dashboard.score.caption": pack("Indice de discipline et de performance", "Discipline and performance index", "Indice de disciplina y rendimiento", "Indice de disciplina e performance"),
    "dashboard.insight.best_setup": pack("Setup le plus performant : {setup}", "Best performing setup: {setup}", "Setup con mejor rendimiento: {setup}", "Setup com melhor performance: {setup}"),
    "dashboard.insight.best_day": pack("Meilleure journee : {value}", "Best day: {value}", "Mejor jornada: {value}", "Melhor dia: {value}"),
    "dashboard.insight.max_drawdown": pack("Drawdown quotidien maximal : {value}", "Maximum daily drawdown: {value}", "Drawdown diario maximo: {value}", "Drawdown diario maximo: {value}"),
    "dashboard.insight.empty_one": pack("Enregistrez les premiers trades pour activer les indicateurs.", "Record your first trades to activate the metrics.", "Registre sus primeros trades para activar las metricas.", "Registre seus primeiros trades para ativar as metricas."),
    "dashboard.insight.empty_two": pack("Le tableau de bord sera actualise automatiquement.", "The dashboard will refresh automatically.", "El panel se actualizara automaticamente.", "O dashboard sera atualizado automaticamente."),
    "dashboard.insight.empty_three": pack("Un jeu de donnees de demonstration peut egalement etre charge.", "A demo dataset can also be loaded.", "Tambien puede cargar un conjunto de datos de demostracion.", "Um conjunto de dados de demonstracao tambem pode ser carregado."),
    "dashboard.chart.win_rate": pack("Taux de reussite", "Win rate", "Tasa de acierto", "Taxa de acerto"),
    "dashboard.chart.consistency": pack("Regularite", "Consistency", "Consistencia", "Consistencia"),
    "dashboard.chart.gain_loss": pack("Gain / perte", "Gain / loss", "Ganancia / perdida", "Ganho / perda"),
    "dashboard.chart.recovery": pack("Recuperation", "Recovery", "Recuperacion", "Recuperacao"),
    "dashboard.chart.drawdown": pack("Drawdown", "Drawdown", "Drawdown", "Drawdown"),
    "transactions.panel.curve": pack("Courbe", "Curve", "Curva", "Curva"),
    "transactions.panel.monthly_gp_history": pack("Historique mensuel des G/P", "Monthly P/L history", "Historial mensual de G/P", "Historico mensal de G/P"),
    "transactions.panel.last_12_months": pack("12 derniers mois", "Last 12 months", "Ultimos 12 meses", "Ultimos 12 meses"),
    "transactions.panel.flow": pack("Flux", "Flow", "Flujo", "Fluxo"),
    "transactions.panel.deposits_withdrawals": pack("Depots et retraits", "Deposits and withdrawals", "Depositos y retiros", "Depositos e retiradas"),
    "transactions.panel.expand_list": pack("Agrandir la liste des transactions", "Expand transactions list", "Ampliar lista de transacciones", "Ampliar lista de transacoes"),
    "transactions.panel.last_two": pack("2 derniers", "Last 2", "Ultimos 2", "Ultimos 2"),
    "transactions.panel.net_month": pack("Net du mois", "Net for the month", "Neto del mes", "Liquido do mes"),
    "transactions.panel.withdrawals_month": pack("Retraits du mois", "Withdrawals this month", "Retiros del mes", "Retiradas do mes"),
    "transactions.panel.deposits_month": pack("Depots du mois", "Deposits this month", "Depositos del mes", "Depositos do mes"),
    "transactions.panel.best_month": pack("Meilleur mois", "Best month", "Mejor mes", "Melhor mes"),
    "transactions.panel.worst_month": pack("Mauvais mois", "Worst month", "Peor mes", "Pior mes"),
    "transactions.panel.history": pack("Historique", "History", "Historial", "Historico"),
    "transactions.panel.monthly_history": pack("Historique mensuel", "Monthly history", "Historial mensual", "Historico mensal"),
    "transactions.panel.gp_flux_stats": pack("G/P, flux et stats", "P/L, flows and stats", "G/P, flujos y estadisticas", "G/P, fluxos e estatisticas"),
    "transactions.modal.capital_flow": pack("Flux de capital", "Capital flow", "Flujo de capital", "Fluxo de capital"),
    "transactions.modal.record_withdrawal": pack("Enregistrer un retrait", "Record a withdrawal", "Registrar un retiro", "Registrar uma retirada"),
    "transactions.modal.record_deposit": pack("Enregistrer un depot", "Record a deposit", "Registrar un deposito", "Registrar um deposito"),
    "transactions.modal.withdrawal_copy": pack("Enregistrez une sortie de capital. Le capital actuel et l historique mensuel sont recalcules a la validation.", "Record a capital outflow. Current capital and monthly history are recalculated on submission.", "Registre una salida de capital. El capital actual y el historial mensual se recalculan al validar.", "Registre uma saida de capital. O capital atual e o historico mensal sao recalculados na validacao."),
    "transactions.modal.deposit_copy": pack("Enregistrez un apport de capital. Le capital actuel et l historique mensuel sont recalcules automatiquement.", "Record a capital deposit. Current capital and monthly history are recalculated automatically.", "Registre una aportacion de capital. El capital actual y el historial mensual se recalculan automaticamente.", "Registre um aporte de capital. O capital atual e o historico mensal sao recalculados automaticamente."),
    "transactions.modal.close": pack("Fermer la fenetre", "Close window", "Cerrar ventana", "Fechar janela"),
    "transactions.form.amount_withdrawal": pack("Montant du retrait", "Withdrawal amount", "Importe del retiro", "Valor da retirada"),
    "transactions.form.amount_deposit": pack("Montant du depot", "Deposit amount", "Importe del deposito", "Valor do deposito"),
    "transactions.form.note": pack("Note", "Note", "Nota", "Nota"),
    "transactions.form.note_withdrawal_placeholder": pack("Ex: retrait mensuel, securisation de performance", "Example: monthly withdrawal, profit lock-in", "Ej: retiro mensual, aseguramiento de beneficios", "Ex: retirada mensal, protecao de lucros"),
    "transactions.form.note_deposit_placeholder": pack("Ex: apport de capital, alimentation du compte", "Example: capital injection, account funding", "Ej: aporte de capital, financiacion de cuenta", "Ex: aporte de capital, financiamento da conta"),
    "transactions.form.withdrawal_caption": pack("Le retrait diminue le capital actuel et s integre a l historique mensuel.", "The withdrawal reduces current capital and is added to monthly history.", "El retiro reduce el capital actual y se integra en el historial mensual.", "A retirada reduz o capital atual e entra no historico mensal."),
    "transactions.form.deposit_caption": pack("Le depot augmente le capital actuel et s integre a l historique mensuel.", "The deposit increases current capital and is added to monthly history.", "El deposito aumenta el capital actual y se integra en el historial mensual.", "O deposito aumenta o capital atual e entra no historico mensal."),
    "transactions.form.record_withdrawal": pack("Enregistrer le retrait", "Record withdrawal", "Registrar retiro", "Registrar retirada"),
    "transactions.form.record_deposit": pack("Enregistrer le depot", "Record deposit", "Registrar deposito", "Registrar deposito"),
    "transactions.modal.all_transactions": pack("Toutes les transactions", "All transactions", "Todas las transacciones", "Todas as transacoes"),
    "transactions.modal.all_transactions_copy": pack("Historique complet des depots et retraits. Faites defiler la liste pour consulter l ensemble des operations.", "Complete history of deposits and withdrawals. Scroll through the list to review all operations.", "Historial completo de depositos y retiros. Desplacese por la lista para revisar todas las operaciones.", "Historico completo de depositos e retiradas. Role a lista para consultar todas as operacoes."),
    "transactions.modal.close_all": pack("Fermer la liste des transactions", "Close transactions list", "Cerrar lista de transacciones", "Fechar lista de transacoes"),
    "transactions.metric.current_capital": pack("Capital actuel", "Current capital", "Capital actual", "Capital atual"),
    "transactions.metric.current_capital_detail": pack("Capital initial {capital} + performances + flux", "Initial capital {capital} + performance + flows", "Capital inicial {capital} + rendimiento + flujos", "Capital inicial {capital} + performance + fluxos"),
    "transactions.metric.trades_month": pack("Trades du mois", "Trades this month", "Trades del mes", "Trades do mes"),
    "transactions.metric.trades_month_detail": pack("{winners} gagnant(s) / {losers} perdant(s)", "{winners} winner(s) / {losers} loser(s)", "{winners} ganador(es) / {losers} perdedor(es)", "{winners} vencedor(es) / {losers} perdedor(es)"),
    "transactions.metric.gp_month": pack("G/P du mois", "Monthly P/L", "G/P del mes", "G/P do mes"),
    "transactions.metric.withdrawals": pack("Retraits", "Withdrawals", "Retiros", "Retiradas"),
    "transactions.metric.withdrawals_detail": pack("{count} operation(s) enregistree(s)", "{count} operation(s) recorded", "{count} operacion(es) registradas", "{count} operacao(oes) registradas"),
    "transactions.metric.deposits": pack("Depots", "Deposits", "Depositos", "Depositos"),
    "transactions.metric.deposits_detail": pack("{count} operation(s) enregistree(s)", "{count} operation(s) recorded", "{count} operacion(es) registradas", "{count} operacao(oes) registradas"),
    "transactions.kind.deposit": pack("Depot", "Deposit", "Deposito", "Deposito"),
    "transactions.kind.withdrawal": pack("Retrait", "Withdrawal", "Retiro", "Retirada"),
    "transactions.movement.saved": pack("{kind} enregistre.", "{kind} recorded.", "{kind} registrado.", "{kind} registrado."),
    "transactions.demo.exists": pack("Des trades sont deja enregistres sur ce compte.", "Trades are already recorded on this account.", "Ya hay trades registrados en esta cuenta.", "Ja existem trades registrados nesta conta."),
    "transactions.demo.loaded": pack("Jeu de donnees de demonstration charge.", "Demo dataset loaded.", "Datos de demostracion cargados.", "Conjunto de demonstracao carregado."),
    "tools.page.title": pack("Outils", "Tools", "Herramientas", "Ferramentas"),
    "tools.header.eyebrow": pack("Boite a outils", "Toolkit", "Caja de herramientas", "Caixa de ferramentas"),
    "tools.header.title": pack("Outils de trading", "Trading tools", "Herramientas de trading", "Ferramentas de trading"),
    "tools.header.copy": pack("Retrouvez les calculateurs essentiels pour calibrer le risque, dimensionner les positions et projeter le capital depuis le compte actif.", "Access the core calculators needed to size risk, define positions, and project capital from the active account.", "Acceda a las calculadoras esenciales para calibrar el riesgo, dimensionar posiciones y proyectar el capital desde la cuenta activa.", "Acesse as calculadoras essenciais para calibrar o risco, dimensionar posicoes e projetar o capital da conta ativa."),
    "tools.back_dashboard": pack("Retour au dashboard", "Back to dashboard", "Volver al panel", "Voltar ao dashboard"),
    "tools.sidebar.capital": pack("Capital actuel", "Current capital", "Capital actual", "Capital atual"),
    "tools.sidebar.capital_copy": pack("Base de travail du compte actif pour les calculateurs de risque, de marge et de projection.", "Working base of the active account for risk, margin, and projection calculators.", "Base de trabajo de la cuenta activa para las calculadoras de riesgo, margen y proyeccion.", "Base de trabalho da conta ativa para as calculadoras de risco, margem e projecao."),
    "tools.metric.current_capital": pack("Capital actuel", "Current capital", "Capital actual", "Capital atual"),
    "tools.metric.current_capital_detail": pack("Reference live pour tous les calculateurs", "Live reference used by all calculators", "Referencia en vivo para todas las calculadoras", "Referencia em tempo real para todas as calculadoras"),
    "tools.metric.risk_one": pack("Risque a 1 %", "1% risk", "Riesgo al 1 %", "Risco a 1%"),
    "tools.metric.risk_two": pack("Risque a 2 %", "2% risk", "Riesgo al 2 %", "Risco a 2%"),
    "tools.metric.currency": pack("Devise du compte", "Account currency", "Moneda de la cuenta", "Moeda da conta"),
    "tools.metric.currency_detail": pack("Toutes les sorties monetaires suivent la devise active", "All monetary outputs follow the active currency", "Todas las salidas monetarias siguen la moneda activa", "Todas as saidas monetarias seguem a moeda ativa"),
    "tools.metric.initial_capital": pack("Capital initial", "Initial capital", "Capital inicial", "Capital inicial"),
    "tools.metric.initial_capital_detail": pack("Reference historique du compte actif", "Historical reference of the active account", "Referencia historica de la cuenta activa", "Referencia historica da conta ativa"),
    "settings.account.edit": pack("Modifier", "Edit", "Editar", "Editar"),
    "settings.account.archive": pack("Archiver", "Archive", "Archivar", "Arquivar"),
    "settings.account.archive_loading": pack("Archivage...", "Archiving...", "Archivando...", "Arquivando..."),
    "settings.account.archive_confirm": pack("Archiver ce compte de trading ?", "Archive this trading account?", "Archivar esta cuenta de trading?", "Arquivar esta conta de trading?"),
    "settings.account.created_on": pack("Cree le {date}", "Created on {date}", "Creado el {date}", "Criado em {date}"),
    "settings.section.base": pack("Base", "Base", "Base", "Base"),
    "settings.section.defaults": pack("Valeurs par defaut", "Default values", "Valores por defecto", "Valores padrao"),
    "settings.section.entry_profile": pack("Profil de saisie", "Entry profile", "Perfil de registro", "Perfil de entrada"),
    "settings.section.entry_profile_copy": pack("Ces parametres alimentent automatiquement le formulaire Nouveau trade afin de standardiser la saisie.", "These settings automatically populate the New trade form to standardize entries.", "Estos parametros alimentan automaticamente el formulario Nuevo trade para estandarizar el registro.", "Esses parametros alimentam automaticamente o formulario Novo trade para padronizar os registros."),
    "settings.section.capital_copy": pack("Le capital actuel evolue avec l activite du compte. Le capital initial reste la base de reference pour l analyse historique.", "Current capital evolves with account activity. Initial capital remains the historical reference.", "El capital actual evoluciona con la actividad de la cuenta. El capital inicial sigue siendo la referencia historica.", "O capital atual evolui com a atividade da conta. O capital inicial continua sendo a referencia historica."),
    "settings.section.account_capital": pack("Capital du compte", "Account capital", "Capital de la cuenta", "Capital da conta"),
    "settings.section.initial_capital": pack("Capital initial", "Initial capital", "Capital inicial", "Capital inicial"),
    "settings.section.initial_gp": pack("G/P sur capital initial", "P/L on initial capital", "G/P sobre capital inicial", "G/P sobre capital inicial"),
    "settings.section.capital_hint": pack("Exemple : avec 1 % de risque et un capital initial de 10 000, l exposition de reference est de 100 dans la devise du compte.", "Example: with 1% risk and an initial capital of 10,000, the reference exposure is 100 in the account currency.", "Ejemplo: con un 1 % de riesgo y un capital inicial de 10 000, la exposicion de referencia es 100 en la moneda de la cuenta.", "Exemplo: com 1% de risco e capital inicial de 10.000, a exposicao de referencia e 100 na moeda da conta."),
    "settings.section.defaults_caption": pack("Les prochaines saisies utiliseront cette configuration par defaut.", "Future entries will use this default configuration.", "Las proximas entradas usaran esta configuracion por defecto.", "Os proximos registros usarao esta configuracao padrao."),
    "settings.section.save": pack("Enregistrer les parametres", "Save settings", "Guardar configuracion", "Salvar configuracoes"),
    "settings.section.save_loading": pack("Enregistrement...", "Saving...", "Guardando...", "Salvando..."),
    "settings.section.summary": pack("Synthese", "Summary", "Resumen", "Resumo"),
    "settings.section.operational_impact": pack("Impact operationnel", "Operational impact", "Impacto operativo", "Impacto operacional"),
    "settings.section.default_direction": pack("Direction par defaut", "Default direction", "Direccion por defecto", "Direcao padrao"),
    "settings.section.default_lots": pack("Lots par defaut", "Default lots", "Lotes por defecto", "Lotes padrao"),
    "settings.section.default_gp": pack("G/P par defaut", "Default P/L", "G/P por defecto", "G/P padrao"),
    "settings.section.default_confidence": pack("Confiance par defaut", "Default confidence", "Confianza por defecto", "Confianca padrao"),
    "settings.section.effects": pack("Effets de configuration", "Configuration effects", "Efectos de configuracion", "Efeitos de configuracao"),
    "settings.section.effects_copy_one": pack("Les champs preconfigures sont injectes dans la modale Nouveau trade pour accelerer la saisie et uniformiser les enregistrements.", "Preconfigured fields are injected into the New trade modal to speed up entry and standardize records.", "Los campos preconfigurados se inyectan en la modal Nuevo trade para acelerar el registro y estandarizar los datos.", "Os campos preconfigurados sao injetados na modal Novo trade para acelerar o registro e padronizar os dados."),
    "settings.section.effects_copy_two": pack("Le capital actuel reflete l etat du compte en temps reel. Le capital initial reste disponible pour mesurer la performance depuis l origine.", "Current capital reflects the live account state. Initial capital remains available to measure performance from inception.", "El capital actual refleja el estado de la cuenta en tiempo real. El capital inicial sigue disponible para medir el rendimiento desde el origen.", "O capital atual reflete o estado da conta em tempo real. O capital inicial permanece disponivel para medir a performance desde o inicio."),
    "settings.section.security": pack("Securite", "Security", "Seguridad", "Seguranca"),
    "settings.section.security_copy": pack("Mettez a jour les identifiants de connexion sans interrompre la session en cours.", "Update login credentials without interrupting the current session.", "Actualice las credenciales de acceso sin interrumpir la sesion actual.", "Atualize as credenciais de acesso sem interromper a sessao atual."),
    "settings.section.password_caption": pack("La mise a jour est immediate et la session en cours est conservee.", "The update is immediate and the current session is preserved.", "La actualizacion es inmediata y la sesion actual se mantiene.", "A atualizacao e imediata e a sessao atual e mantida."),
    "settings.section.password_submit": pack("Changer le mot de passe", "Change password", "Cambiar contrasena", "Alterar senha"),
    "settings.section.password_loading": pack("Mise a jour...", "Updating...", "Actualizando...", "Atualizando..."),
    "settings.section.delete": pack("Supprimer mon compte", "Delete my account", "Eliminar mi cuenta", "Excluir minha conta"),
    "settings.section.delete_copy": pack("Cette action est irreversible. L ensemble des preferences, comptes, mouvements et trades sera supprime.", "This action is irreversible. All preferences, accounts, movements, and trades will be deleted.", "Esta accion es irreversible. Se eliminaran todas las preferencias, cuentas, movimientos y trades.", "Esta acao e irreversivel. Todas as preferencias, contas, movimentos e trades serao excluidos."),
    "settings.section.delete_caption": pack("Apres confirmation, le compte sera supprime et la session sera redirigee vers la page de connexion.", "After confirmation, the account will be deleted and the session will be redirected to the login page.", "Tras la confirmacion, la cuenta se eliminara y la sesion sera redirigida a la pagina de acceso.", "Apos a confirmacao, a conta sera excluida e a sessao sera redirecionada para a pagina de login."),
    "settings.section.delete_loading": pack("Suppression...", "Deleting...", "Eliminando...", "Excluindo..."),
    "settings.modal.accounts": pack("Comptes", "Accounts", "Cuentas", "Contas"),
    "settings.modal.add_account": pack("Ajouter un compte", "Add account", "Agregar cuenta", "Adicionar conta"),
    "settings.modal.add_account_copy": pack("Creez un nouveau compte de trading rattache au meme utilisateur. Il peut etre defini comme compte actif des sa creation.", "Create a new trading account linked to the same user. It can be set as the active account immediately.", "Cree una nueva cuenta de trading vinculada al mismo usuario. Puede definirse como cuenta activa inmediatamente.", "Crie uma nova conta de trading vinculada ao mesmo usuario. Ela pode ser definida como conta ativa imediatamente."),
    "settings.modal.close_create": pack("Fermer la creation de compte", "Close account creation", "Cerrar creacion de cuenta", "Fechar criacao de conta"),
    "settings.modal.create_caption": pack("Le compte peut etre active immediatement apres validation.", "The account can be activated immediately after submission.", "La cuenta puede activarse inmediatamente despues de validar.", "A conta pode ser ativada imediatamente apos a validacao."),
    "settings.modal.create_loading": pack("Creation...", "Creating...", "Creando...", "Criando..."),
    "settings.modal.edit_account": pack("Modifier un compte", "Edit account", "Editar cuenta", "Editar conta"),
    "settings.modal.edit_account_copy": pack("Mettez a jour les informations de reference du compte selectionne : nom, broker, identifiant, devise et capital initial.", "Update the reference information of the selected account: name, broker, identifier, currency, and initial capital.", "Actualice la informacion de referencia de la cuenta seleccionada: nombre, broker, identificador, moneda y capital inicial.", "Atualize as informacoes de referencia da conta selecionada: nome, broker, identificador, moeda e capital inicial."),
    "settings.modal.close_edit": pack("Fermer la modification de compte", "Close account editing", "Cerrar edicion de cuenta", "Fechar edicao de conta"),
    "settings.modal.edit_caption": pack("Si ce compte est actif, les parametres et le capital de reference sont resynchronises automatiquement.", "If this account is active, settings and reference capital are synchronized automatically.", "Si esta cuenta esta activa, los parametros y el capital de referencia se resincronizan automaticamente.", "Se esta conta estiver ativa, as configuracoes e o capital de referencia sao resincronizados automaticamente."),
    "settings.modal.edit_submit": pack("Enregistrer les modifications", "Save changes", "Guardar cambios", "Salvar alteracoes"),
    "settings.account.archived_badge": pack("Archive", "Archived", "Archivada", "Arquivada"),
    "settings.account.archived_on": pack("Archive le {date}", "Archived on {date}", "Archivada el {date}", "Arquivada em {date}"),
    "settings.account.restore": pack("Restaurer", "Restore", "Restaurar", "Restaurar"),
    "settings.account.restore_loading": pack("Restauration...", "Restoring...", "Restaurando...", "Restaurando..."),
    "settings.modal.archived_accounts": pack("Comptes archives", "Archived accounts", "Cuentas archivadas", "Contas arquivadas"),
    "settings.modal.archived_copy": pack("Les comptes archives sont exclus du changement rapide et des statistiques actives jusqu a leur restauration.", "Archived accounts are excluded from quick switching and active statistics until restored.", "Las cuentas archivadas quedan excluidas del cambio rapido y de las estadisticas activas hasta su restauracion.", "As contas arquivadas ficam excluidas da troca rapida e das estatisticas ativas ate serem restauradas."),
    "settings.modal.close_archived": pack("Fermer la liste des comptes archives", "Close archived accounts list", "Cerrar lista de cuentas archivadas", "Fechar lista de contas arquivadas"),
    "settings.modal.no_archived": pack("Aucun compte archive disponible.", "No archived account available.", "No hay cuentas archivadas disponibles.", "Nenhuma conta arquivada disponivel."),
    "auth.mobile.open_login": pack("Ouvrir la connexion", "Open sign-in", "Abrir inicio de sesion", "Abrir login"),
    "auth.mobile.open_register": pack("Ouvrir l inscription", "Open registration", "Abrir registro", "Abrir cadastro"),
    "auth.mobile.close": pack("Fermer le formulaire", "Close form", "Cerrar formulario", "Fechar formulario"),
    "switcher.title": pack("Changer de compte", "Switch account", "Cambiar cuenta", "Trocar conta"),
    "switcher.subtitle": pack("Selectionnez rapidement un autre compte de trading depuis cette fenetre.", "Quickly select another trading account from this window.", "Seleccione rapidamente otra cuenta de trading desde esta ventana.", "Selecione rapidamente outra conta de trading nesta janela."),
    "switcher.manage_accounts": pack("Gerer les comptes", "Manage accounts", "Gestionar cuentas", "Gerenciar contas"),
    "currency.usd": pack("Dollar americain (USD)", "US dollar (USD)", "Dolar estadounidense (USD)", "Dolar americano (USD)"),
    "currency.eur": pack("Euro (EUR)", "Euro (EUR)", "Euro (EUR)", "Euro (EUR)"),
    "currency.gbp": pack("Livre sterling (GBP)", "British pound (GBP)", "Libra esterlina (GBP)", "Libra esterlina (GBP)"),
    "currency.chf": pack("Franc suisse (CHF)", "Swiss franc (CHF)", "Franco suizo (CHF)", "Franco suico (CHF)"),
    "currency.xaf": pack("Franc CFA BEAC (XAF)", "Central African CFA franc (XAF)", "Franco CFA BEAC (XAF)", "Franco CFA BEAC (XAF)"),
    "currency.xof": pack("Franc CFA BCEAO (XOF)", "West African CFA franc (XOF)", "Franco CFA BCEAO (XOF)", "Franco CFA BCEAO (XOF)"),
    "form.preferences.default_symbol": pack("Paire par defaut", "Default pair", "Par por defecto", "Par padrao"),
    "form.preferences.default_direction": pack("Direction par defaut", "Default direction", "Direccion por defecto", "Direcao padrao"),
    "form.preferences.default_setup": pack("Setup par defaut", "Default setup", "Setup por defecto", "Setup padrao"),
    "form.preferences.default_lots": pack("Quantite par defaut (lots)", "Default size (lots)", "Tamano por defecto (lotes)", "Quantidade padrao (lotes)"),
    "form.preferences.default_gp": pack("G/P par defaut", "Default P/L", "G/P por defecto", "G/P padrao"),
    "form.preferences.default_confidence": pack("Confiance par defaut", "Default confidence", "Confianza por defecto", "Confianca padrao"),
    "form.preferences.active_initial_capital": pack("Capital initial du compte actif", "Initial capital of the active account", "Capital inicial de la cuenta activa", "Capital inicial da conta ativa"),
    "form.preferences.active_currency": pack("Devise du compte actif", "Active account currency", "Moneda de la cuenta activa", "Moeda da conta ativa"),
    "form.account.name": pack("Nom du compte", "Account name", "Nombre de la cuenta", "Nome da conta"),
    "form.account.broker": pack("Broker", "Broker", "Broker", "Broker"),
    "form.account.identifier": pack("Numero / identifiant", "Number / identifier", "Numero / identificador", "Numero / identificador"),
    "form.account.initial_capital": pack("Capital initial", "Initial capital", "Capital inicial", "Capital inicial"),
    "form.account.currency": pack("Devise", "Currency", "Moneda", "Moeda"),
    "form.account.name.placeholder": pack("Ex: Compte principal, FTMO Swing, Prop Firm", "Example: Main account, FTMO Swing, Prop Firm", "Ej: Cuenta principal, FTMO Swing, Prop Firm", "Ex: Conta principal, FTMO Swing, Prop Firm"),
    "form.account.broker.placeholder": pack("Ex: IC Markets, FTMO, Exness", "Example: IC Markets, FTMO, Exness", "Ej: IC Markets, FTMO, Exness", "Ex: IC Markets, FTMO, Exness"),
    "form.account.identifier.placeholder": pack("Ex: 50124587", "Example: 50124587", "Ej: 50124587", "Ex: 50124587"),
    "form.account.set_active_on_create": pack("Definir ce compte comme actif a la creation", "Set this account as active on creation", "Definir esta cuenta como activa al crearla", "Definir esta conta como ativa na criacao"),
    "form.account.set_active_on_update": pack("Definir ce compte comme actif apres la mise a jour", "Set this account as active after update", "Definir esta cuenta como activa despues de la actualizacion", "Definir esta conta como ativa apos a atualizacao"),
    "form.password.current": pack("Mot de passe actuel", "Current password", "Contrasena actual", "Senha atual"),
    "form.password.current.placeholder_change": pack("Mot de passe actuel", "Current password", "Contrasena actual", "Senha atual"),
    "form.password.new": pack("Nouveau mot de passe", "New password", "Nueva contrasena", "Nova senha"),
    "form.password.new.placeholder_change": pack("Saisissez le nouveau mot de passe", "Enter the new password", "Introduzca la nueva contrasena", "Digite a nova senha"),
    "form.password.confirm.placeholder_change": pack("Confirmez le nouveau mot de passe", "Confirm the new password", "Confirme la nueva contrasena", "Confirme a nova senha"),
    "form.delete.password.placeholder": pack("Confirmez votre mot de passe", "Confirm your password", "Confirme su contrasena", "Confirme sua senha"),
    "form.delete.confirmation": pack("Je confirme la suppression definitive de mon compte et de l ensemble de mes donnees.", "I confirm the permanent deletion of my account and all my data.", "Confirmo la eliminacion definitiva de mi cuenta y de todos mis datos.", "Confirmo a exclusao definitiva da minha conta e de todos os meus dados."),
    "form.delete.confirmation_required": pack("La confirmation de suppression est requise.", "Deletion confirmation is required.", "La confirmacion de eliminacion es obligatoria.", "A confirmacao de exclusao e obrigatoria."),
    "form.delete.invalid_password": pack("Le mot de passe saisi est incorrect.", "The entered password is incorrect.", "La contrasena introducida es incorrecta.", "A senha informada esta incorreta."),
    "form.movement.note.placeholder": pack("Ex: retrait mensuel, apport de capital, ajustement de compte...", "Example: monthly withdrawal, capital injection, account adjustment...", "Ej: retiro mensual, aporte de capital, ajuste de cuenta...", "Ex: retirada mensal, aporte de capital, ajuste de conta..."),
    "form.trade.gp_required": pack("Le champ G/P est requis pour calculer le risque.", "The P/L field is required to calculate risk.", "El campo G/P es obligatorio para calcular el riesgo.", "O campo G/P e obrigatorio para calcular o risco."),
    "views.login.title": pack("Connexion", "Sign in", "Iniciar sesion", "Entrar"),
    "views.register.title": pack("Inscription", "Register", "Registro", "Cadastro"),
    "views.success.configuration_saved": pack("Configuration enregistree.", "Configuration saved.", "Configuracion guardada.", "Configuracao salva."),
    "views.success.account_created": pack("Compte de trading cree.", "Trading account created.", "Cuenta de trading creada.", "Conta de trading criada."),
    "views.error.account_missing": pack("Compte de trading introuvable.", "Trading account not found.", "Cuenta de trading no encontrada.", "Conta de trading nao encontrada."),
    "views.success.account_updated": pack("Compte mis a jour : {account}.", "Account updated: {account}.", "Cuenta actualizada: {account}.", "Conta atualizada: {account}."),
    "views.success.account_activated": pack("Compte actif defini sur {account}.", "Active account set to {account}.", "La cuenta activa ahora es {account}.", "Conta ativa definida como {account}."),
    "views.error.account_activate_failed": pack("Activation du compte impossible.", "Unable to activate account.", "No fue posible activar la cuenta.", "Nao foi possivel ativar a conta."),
    "views.error.account_archive_failed": pack("Archivage du compte impossible.", "Unable to archive account.", "No fue posible archivar la cuenta.", "Nao foi possivel arquivar a conta."),
    "views.error.account_restore_failed": pack("Restauration du compte impossible.", "Unable to restore account.", "No fue posible restaurar la cuenta.", "Nao foi possivel restaurar a conta."),
    "views.success.password_updated": pack("Mot de passe mis a jour.", "Password updated.", "Contrasena actualizada.", "Senha atualizada."),
}


def normalize_language(code):
    normalized = (code or DEFAULT_LANGUAGE).strip().lower().replace("_", "-")
    aliases = {
        "fr-fr": "fr",
        "en-us": "en",
        "en-gb": "en",
        "es-es": "es",
        "pt-br": "pt",
        "pt-pt": "pt",
        "ar-sa": "ar",
        "zh": "zh-hans",
        "zh-cn": "zh-hans",
    }
    normalized = aliases.get(normalized, normalized)
    if normalized in LANGUAGE_META:
        return normalized
    base_code = normalized.split("-", 1)[0]
    return base_code if base_code in LANGUAGE_META else DEFAULT_LANGUAGE


def get_current_language_code():
    return normalize_language(get_language())


def get_language_locale(language=None):
    code = normalize_language(language or get_current_language_code())
    return LANGUAGE_META[code]["locale"]


def get_language_direction(language=None):
    code = normalize_language(language or get_current_language_code())
    return "rtl" if code in RTL_LANGUAGES else "ltr"


def get_language_menu(language=None):
    current = normalize_language(language or get_current_language_code())
    return [
        {
            "code": code,
            "native_name": meta["native_name"],
            "english_name": meta["english_name"],
            "is_active": code == current,
        }
        for code, meta in LANGUAGE_META.items()
    ]


def translate(key, language=None, default=None, **kwargs):
    code = normalize_language(language or get_current_language_code())
    value = TRANSLATIONS.get(key, {}).get(code)
    if value is None:
        value = TRANSLATIONS.get(key, {}).get(DEFAULT_LANGUAGE, default or key)
    return value.format(**kwargs) if kwargs else value


def get_weekday_short_labels(language=None):
    code = normalize_language(language or get_current_language_code())
    return WEEKDAY_SHORT.get(code, WEEKDAY_SHORT[DEFAULT_LANGUAGE])
